---
title: "Comparison of Curb-facing Sidewalks and Census Indicators of Pedestrian Activity in Waterloo, ON"
author: "Craig A. Sloss"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(sf)
library(leaflet)
library(ggplot2)
library(RColorBrewer)
census = readRDS("./data/snow_clearing_dataset.rds")
percentage_walk_dataset = census %>%
  filter(CHARACTERISTIC_NAME %in% c("Walked", "Public transit")) %>%
  group_by(GEO_NAME) %>%
  summarise(walk_or_transit = sum(C10_RATE_TOTAL, na.rm = TRUE))
waterloo_map = read_sf(dsn = "./data/waterloo", layer = "waterloo_DA") %>% 
  st_transform("+proj=longlat +datum=WGS84") %>%
  left_join(percentage_walk_dataset %>% rename(DAUID = GEO_NAME)) %>%
  subset(!is.na(walk_or_transit))
sidewalk_map = read_sf(dsn = "./data/Sidewalks-shp", layer = "Sidewalks") %>% 
  st_transform("+proj=longlat +datum=WGS84")
school_map = read_sf(dsn = "./data/Schools", layer = "Schools") %>%
  st_transform("+proj=longlat +datum=WGS84")
road_map = read_sf(dsn = "./data/Roads", layer = "Roads") %>% 
  st_transform("+proj=longlat +datum=WGS84")
```

#### Responsibility for Sidewalk Snow Clearing
```{r}
pal <- colorFactor(palette = "Accent", domain = sidewalk_map$BLVD_TYPE)
leaflet(sidewalk_map %>%  filter(!BLVD_TYPE %in% c("N/A", NA))) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(color = ~pal(BLVD_TYPE), opacity = 1, weight = 2) %>%
  addLegend(pal = pal, values = ~BLVD_TYPE, title = "")
```

```{r}
pal <- colorFactor(palette = "Accent", domain = sidewalk_map$CLEARED_BY)
leaflet(sidewalk_map) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(color = ~pal(CLEARED_BY), opacity = 1, weight = 2) %>%
  addLegend(pal = pal, values = ~CLEARED_BY, title = "")
```


```{r}
pal <- colorNumeric(
  palette = "Purples",
  domain = waterloo_map$walk_or_transit
)
leaflet(waterloo_map) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = waterloo_map,
              weight = 0,
              color = ~pal(walk_or_transit),
              fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~walk_or_transit, title = "% sidewalk commuters") %>%
  addPolylines(data = sidewalk_map %>% filter(BLVD_TYPE == "Curb Face"),
               color = "#D55E00", 
               opacity = 1, 
               weight = 2)

```

```{r}
leaflet(waterloo_map) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(data = sidewalk_map %>% filter(BLVD_TYPE == "Curb Face"),
               color = "green", 
               opacity = 1, 
               weight = 2) %>%
  addMarkers(data = school_map %>% filter(CLASS %in% c("ELEMENTARY", "SECONDARY")),
             label = ~NAME) %>%
  addPolylines(data = road_map %>% filter(MANAGED_BY == "Region of Waterloo"), color = "purple", opacity = 1, weight = 2)
```


```{r}
pal <- colorNumeric(
  palette = "Oranges",
  domain = waterloo_map$walk_or_transit
)
sidewalk_map = sidewalk_map %>%
  mutate(BLVD_TYPE_BY_RESPONSIBILITY = case_when(
    BLVD_TYPE == "Curb Face" & CLEARED_BY == "City Crews" ~ "Curb Face - Cleared by City",
    BLVD_TYPE == "Curb Face" & CLEARED_BY != "City Crews" ~ "Curb Face - Not Cleared by City",
    TRUE ~ "Not Curb Face"
  ))
pal_sidewalk <- colorFactor(palette = "Accent", domain = sidewalk_map$BLVD_TYPE_BY_RESPONSIBILITY)
leaflet(waterloo_map) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolygons(data = waterloo_map,
              weight = 0,
              color = ~pal(walk_or_transit),
              fillOpacity = 0.5) %>%
  addLegend(pal = pal, values = ~walk_or_transit, title = "") %>%
  addPolylines(data = sidewalk_map %>% filter(BLVD_TYPE == "Curb Face"),
               color = ~pal_sidewalk(BLVD_TYPE_BY_RESPONSIBILITY), 
               opacity = 1, 
               weight = 2)

```


# Regional Roads



```{r}
pal <- colorFactor(palette = "Accent", domain = road_map$MANAGED_BY)
leaflet(road_map) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(color = ~pal(MANAGED_BY), opacity = 1, weight = 2) %>%
  addLegend(pal = pal, values = ~MANAGED_BY, title = "")
```

```{r}
road_map = road_map %>% mutate(REGIONAL_ROAD_INDICATOR = ifelse(MANAGED_BY == "Region of Waterloo", "Regional Road", "Other"))
pal <- colorFactor(palette = "Dark2", domain = road_map$REGIONAL_ROAD_INDICATOR)
leaflet(road_map %>% filter(MANAGED_BY != "Region of Waterloo")) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(color = "grey", opacity = 1, weight = 1) %>%
  addPolylines(data = road_map %>% filter(MANAGED_BY == "Region of Waterloo"), color = "red", opacity = 1, weight = 2)
  #addLegend(pal = pal, values = ~REGIONAL_ROAD_INDICATOR, title = "")
```

TODO:
- Highlight regional roads vs others
- Overlay what the city currently clears
- Overlay pedestrian / cyclist activity

#### Data sources 

* Statistics Canada, 2021 Census of Population (https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/download-telecharger.cfm?Lang=E)

* Statistics Canada, 2021 Census Boundaries (https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/index2021-eng.cfm?Year=21)

* City of Waterloo Open Data, 2019 Sidewalks (https://data.waterloo.ca/datasets/City-of-Waterloo::sidewalks/about)

* City of Waterloo Open Data, 2018 Schools (https://data.waterloo.ca/datasets/City-of-Waterloo::schools/about)
